services:
  ros2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros2
    volumes:
      - ..:/workspace:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_LOCALHOST_ONLY=1
    network_mode: host
  