---
name: ROS2-jazzyのDockerイメージのビルド

on: 
  push:
    branches:
      - ros2-jazzy
  schedule:
    - cron: '0 15 */1 * *'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Build
        uses: docker/build-push-action@v6
        with:
          file: .devcontainer/Dockerfile
          tags: ros2:jazzy

